import { type NextPage } from "next";
import Header from "../components/header";
import SideNav from "../components/sideNav";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession } from "next-auth/react";
import JobList from '../components/dashboardComponents/joblist'


const Patients: NextPage = () => {

  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const { data: sessionData } = useSession();
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <>
    <Head>
      <title>Dashboard</title>
        {/* Update Later */}
        {/* <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" /> */}
    </Head>
    < Header />
    <div className="flex flex-row">
      <div className="basis-1/4">
        < SideNav /> 
      </div>
      <div className="basis-1/2">
        < JobList />
      </div>






    </div>
    















    {/* TEPORARY CLOSE THE SERVER CONNENTIONS */}
    {/* <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <p className="text-2xl text-white">
        Patients Dashboard
      </p>
      <p className="text-2xl text-white">
        {sessionData && <span>{sessionData.user?.name}</span>}
      </p>
      <p className="text-2xl text-white">
        {hello.data ? hello.data.meow : "Loading tRPC query..."}
      </p>
      <p className="text-2xl text-white">
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <p className="text-2xl text-white">
        {hello.data ? hello.data.date?.toLocaleDateString(undefined)  : "Loading tRPC query..."}
      </p>
    </div> */}

</>
  );
};

export default Patients;
