import { type NextPage } from "next";
import Header from "../components/header";
import SideNav from "../components/sideNav";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession } from "next-auth/react";
import { Table } from 'flowbite-react'


const Patients: NextPage = () => {

  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const { data: sessionData } = useSession();
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <>
    <Head>
      <title>Dashboard</title>
        {/* Update Later */}
        {/* <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" /> */}
    </Head>
    < Header />
    <div className="flex flex-row">
      <div className="basis-1/4">
      < SideNav /> 
      </div>
      <div className="basis-1/2">
      <Table hoverable={true}>
      <Table.Head>
        <Table.HeadCell>
          Patient Need
        </Table.HeadCell>
        <Table.HeadCell>
          Location
        </Table.HeadCell>
        <Table.HeadCell>
          Special Needs
        </Table.HeadCell>
        <Table.HeadCell>
          Compensation
        </Table.HeadCell>
        <Table.HeadCell>
          <span className="sr-only">
            Edit
          </span>
        </Table.HeadCell>
      </Table.Head>
      <Table.Body className="divide-y">
        <Table.Row className="bg-white dark:border-gray-700 dark:bg-gray-800">
          <Table.Cell className="whitespace-nowrap font-medium text-gray-900 dark:text-white">
            Conversation & Bathing
          </Table.Cell>
          <Table.Cell>
            San Jose
          </Table.Cell>
          <Table.Cell>
            None
          </Table.Cell>
          <Table.Cell>
            $25 / hour
          </Table.Cell>
          <Table.Cell>
            <a
              href="/tables"
              className="font-medium text-blue-600 hover:underline dark:text-blue-500"
            >
              Learn More
            </a>
          </Table.Cell>
        </Table.Row>
        <Table.Row className="bg-white dark:border-gray-700 dark:bg-gray-800">
          <Table.Cell className="whitespace-nowrap font-medium text-gray-900 dark:text-white">
            Microsoft Surface Pro
          </Table.Cell>
          <Table.Cell>
            White
          </Table.Cell>
          <Table.Cell>
            Laptop PC
          </Table.Cell>
          <Table.Cell>
            $1999
          </Table.Cell>
          <Table.Cell>
            <a
              href="/tables"
              className="font-medium text-blue-600 hover:underline dark:text-blue-500"
            >
              Edit
            </a>
          </Table.Cell>
        </Table.Row>
        <Table.Row className="bg-white dark:border-gray-700 dark:bg-gray-800">
          <Table.Cell className="whitespace-nowrap font-medium text-gray-900 dark:text-white">
            Magic Mouse 2
          </Table.Cell>
          <Table.Cell>
            Black
          </Table.Cell>
          <Table.Cell>
            Accessories
          </Table.Cell>
          <Table.Cell>
            $99
          </Table.Cell>
          <Table.Cell>
            <a
              href="/tables"
              className="font-medium text-blue-600 hover:underline dark:text-blue-500"
            >
              Edit
            </a>
          </Table.Cell>
        </Table.Row>
      </Table.Body>
    </Table>

      </div>






    </div>
    















    {/* TEPORARY CLOSE THE SERVER CONNENTIONS */}
    {/* <div className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <p className="text-2xl text-white">
        Patients Dashboard
      </p>
      <p className="text-2xl text-white">
        {sessionData && <span>{sessionData.user?.name}</span>}
      </p>
      <p className="text-2xl text-white">
        {hello.data ? hello.data.meow : "Loading tRPC query..."}
      </p>
      <p className="text-2xl text-white">
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <p className="text-2xl text-white">
        {hello.data ? hello.data.date?.toLocaleDateString(undefined)  : "Loading tRPC query..."}
      </p>
    </div> */}

</>
  );
};

export default Patients;
