import { type NextPage } from "next";
import Header from "../components/header";
import SideNav from "../components/sideNav";
import Head from "next/head";

const Help: NextPage = () => {

  return (
    <>
    < Header />
    < SideNav />
    <Head>
      <title>Help</title>
        {/* Update Later */}
        {/* <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" /> */}
    </Head>
    
    <div>
      Help Information and tools here
    </div>
    </>
  );
};

export default Help;
