import { type NextPage } from "next";
import Header from "../components/header";
import SideNav from "../components/sideNav";
import Head from "next/head";

const Messages: NextPage = () => {

  return (
    <>
    <Head>
      <title>Messages</title>
        {/* Update Later */}
        {/* <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" /> */}
    </Head>
    < Header />
    < SideNav />
    <div>
      Messages here
    </div>
    </>
  );
};

export default Messages;
